export const GET_STORIES_BEGIN = "GET_STORIES_BEGIN";
export const GET_STORIES_SUCCESS = "GET_STORIES_SUCCESS";
export const GET_STORIES_ERROR = "GET_STORIES_ERROR";
export const GET_SINGLE_STORY_BEGIN = "GET_SINGLE_STORY_BEGIN";
export const GET_SINGLE_STORY_SUCCCESS = "GET_SINGLE_STORY_SUCCCESS";
export const GET_SINGLE_STORY_ERROR = "GET_SINGLE_STORY_ERROR";

export type StoryActionType = {
  GET_STORIES_BEGIN: "GET_STORIES_BEGIN";
  GET_STORIES_SUCCESS: "GET_STORIES_SUCCESS";
  GET_STORIES_ERROR: "GET_STORIES_ERROR";
  GET_SINGLE_STORY_BEGIN: "GET_SINGLE_STORY_BEGIN";
  GET_SINGLE_STORY_SUCCCESS: "GET_SINGLE_STORY_SUCCCESS";
  GET_SINGLE_STORY_ERROR: "GET_SINGLE_STORY_ERROR";
};

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export type LoginActionType = {
  LOGIN_START: "LOGIN_START";
  LOGIN_SUCCESS: "LOGIN_SUCCESS";
  LOGIN_ERROR: "LOGIN_ERROR";
};
